# Generated by Django 6.0.2 on 2026-02-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
