# Generated by Django 6.0.2 on 2026-02-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_rename_category_id_course_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(upload_to='media/materials/'),
        ),
    ]
